### ISSUE TITLE
Logging does not work with pennylane

### ISSUE THREAD

**Issue by frederikwilde** [XanaduAI/pennylane#207]
It seems that importing pennylane prevents the ```logging``` module from writing log entries to a file. When executing the following
```python
import pennylane
import logging
logging.basicConfig(filename='logfile.log',level=logging.DEBUG)
logging.debug('A log entry.')
```
no file ```logfile.log``` is created in the current directory, and if such a file exists already nothing is written to it. However, after commenting out the first line, everything works fine.

#### System information

* **Operating system:** macOS Mojave, Version 10.14.4
* **PennyLane version:** Pennylane 0.3.1
* **Python version:** Python 3.7.2
* **NumPy and SciPy versions:** Numpy 1.16.3, SciPy 1.2.1

* **Installation method:** pip 19.1.1

**Comment by co9olguy** [comment]
Thanks for the bug report @frederikwilde! We'll take a look and see if we can figure out what the root of the problem is.

**Comment by josh146** [comment]
HI @frederikwilde, I've merged in #208, which cleans up the internal logging in PennyLane, and removes logging configuration - so it should no longer clash with user specified log configs.

However, it is still recommended to import and set up logging before importing PennyLane:
```python
import logging
logging.basicConfig(filename='logfile.log',level=logging.DEBUG)
logging.debug('A log entry.')

import pennylane
```

This is because there are some messages that may be logged (regarding configuration files) on import.

**Comment by frederikwilde** [comment]
@josh146  That was quick. Thanks a lot!

**Comment by qlan3** [comment]
Somehow, I still have this problem with PennyLane==0.19.1 and PennyLane-Lightning==0.19.0.

**Comment by Jaybsoni** [comment]
Hi @qlan3, 
 
> Somehow, I still have this problem with PennyLane==0.19.1 and PennyLane-Lightning==0.19.0.

Sorry to hear that! Would you be able to fill out a GitHub issue about this or comment the code that is causing you trouble? Then we can have a look at it for you ! 

Cheers,
